### ISSUE TITLE
linked storehouse HR graphics seems outdated compared to all others

### ISSUE THREAD

**Issue by hgschmie** [Warehousing/Warehousing#120]
compare https://github.com/Warehousing/Warehousing/blob/master/src/graphics/entity/storehouse/storehouse-linked.png 

with 

https://github.com/Warehousing/Warehousing/blob/master/src/graphics/entity/storehouse/hr-storehouse-active-provider.png

e.g.

<img width="415" alt="Screenshot 2024-11-14 at 11 21 35" src="https://github.com/user-attachments/assets/19daf18b-a4ae-4078-8b1a-39e7ba61e1bb">

the linked storehouse doesn't match all the other storehouses.

**Comment by dgw** [comment]
Huh, that is odd. I admit to not testing the Linked variants much in #88 since they aren't available in a normal game.

Let's see if @Anoyomouse has the graphics assets, or if not we can try to reach @snouz.

It can probably be fixed as a pixel edit if necessary, but first I'd like to see if we can do it "the right way". There's some other graphics stuff going on in #118 that I'd rather finish up before moving on to this, anyway.

**Comment by dgw** [comment]
Aww, too bad @ sources. I'll try to get to this by the end of this weekend. Gives @snouz a few more days to surface and rescue me from pixel peeping 🙃

**Comment by dgw** [comment]
@hgschmie Have a look at #123, and let me know if I missed anything stupid :)
