### ISSUE TITLE
Rebalance tech requirements of logistics warehousing

### ISSUE THREAD

**Issue by mkaito** [Warehousing/Warehousing#19]
Hi!

Now that Logistics is behind yellow science, I think Logistics Warehousing should not require it to be researched first.

Use case: Using storage and passive provider warehouses before Logistics is researched.

I don't think it should require purple science either, but that's another discussion.

**Comment by dgw** [comment]
If anything, the case to be made here is for a split research. Passive provider and storage storehouse/warehouse should be available from a research that unlocks after both `construction-robotics` and the base Warehouse research are complete. The remaining warehouse types (active provider and requester) would require this new research, as well as `logistic-system` from the base game. Science pack types would be split too, and based on the corresponding research to unlock that type of logistic chest.

I don't want to jump too hard on this, but if 0.16 isn't out "soon" the tech requirements will get updated as a standalone update, assuming @Anoyomouse can push the release out for me when it's ready.

Thanks for getting me to take another look at the research, @mkaito. I found another thing I'd personally like to fix at the same time as this is addressed.

**Comment by Anoyomouse** [comment]
Hey

Sure, I can release a new version for you when you're ready, put it in releases and poke me and I'll deploy it within 24 hours (allowing for timezones) should be quicker than that though!


Sent from my BlackBerry - the most secure mobile device

**Comment by mkaito** [comment]
There are people out there who feel like requiring yellow science for Logistics tech is too far up the tech tree. I think it's fair to allow players to choose, since it's easy to mod the requirements of a tech anyway (and there are at least two such mods on the portal that I know of).

If at all possible, do you think you could base the requirements of logistics warehousing on the actual requirements of logistics tech?

**Comment by dgw** [comment]
I'll investigate doing so, though I can't promise that will make it into the initial release for 0.16. The current plan is to just make the mod work as-is in the new Factorio release, then add enhancements later in patches once 0.16 stabilizes a bit more.

**Comment by mkaito** [comment]
That's fine, I just thought I'd suggest it since you'll be looking into tech requirements.

**Comment by olitologie** [comment]
@dgw @mkaito The recipes could get an update for example tech 1:
40 x science 1
40 x science 2
I think its fare to cheap at beginning (compare it with electricity).

The tech stage 2 maybe reduce the science package 1 and 2 to only consume 1 except of 2 and add the high technologies pack (compared with the logistic tech):
40 x science 1
40 x science 2
40 x science 3
40 x production
40 x hightech

**Comment by dgw** [comment]
> If at all possible, do you think you could base the requirements of logistics warehousing on the actual requirements of logistics tech?

@mkaito, this is on track to be included in the next release. Can't guarantee it'll work with all mods, but I did put it as late in the loading process as possible. Logistics research–altering mods that are not compatible will have to be added as optional dependencies to force the game to load their changes first.

**Comment by dgw** [comment]
With the merging of #34, Warehousing will adapt the cost of logistic warehousing to accommodate mods that alter the cost of the Logistic System research.

Is it still desired to have separate researches for passive/storage & active/requester/buffer logistic types?

**Comment by Anoyomouse** [comment]
I haven't really played Factorio seriously for ages, however, i would say that if the base game's research is broken up (tiered) then the warehousing research should be tiered to match (can guess getting certain warehouses - and logistic chests - before others would be a massive plus for anyone)

**Comment by dgw** [comment]
Another option would be to do away with separate researches altogether, and lump the logistic storehouses/warehouses in with the base-game techs that unlock the equivalent chests. It'd take an event listener to unlock the appropriate recipes `on_research_finished`, depending on whether the player/force researches Warehousing before or after the logistic techs, but it wouldn't require a new technology icon (which splitting the research would).

The two solutions I see are:

1. Split the existing **Logistics Warehousing** tech into two tiers.
    * **Logistics Warehousing Tier 1**
      * Prerequisites: **Warehousing** & ( **Construction Robotics** OR **Logistic Robotics** )
      * Unlocks: Passive Provider & Storage variants of storehouse/warehouse
    * **Logistics Warehousing Tier 2**
      * Prerequisites: **Logistics Warehousing Tier 1** & **Logistic System**
      * Unlocks: Active Provider, Buffer, & Requester variants of storehouse/warehouse
    * Would require _at minimum_ a new icon for the second tier, and maybe a refresh of the existing icon for **Logistics Warehousing** (which could be used for tier 1 as-is, at least temporarily).
    * _Note: I haven't come up with creative names for the techs yet, but I will if we go this route._
    * _Note 2: I'm not sure yet how to implement the OR in prerequisites for tier 1. Since the base game makes passive provider and storage chests available if the player researches either logistic or construction robotics, Warehousing would also have to make the first tier of logistic warehouses available if only one or the other is unlocked—i.e. **not** require both. Maybe the technology needs to start out with `enabled = false` and get enabled by an `on_research_finished` event listener… and have a migration to make it available if added to a game with logistic and/or construction robotics already researched. Will have to look further into this when I have time (and when it's not 2am 😂 ), if this is the chosen route._
2. Dump the Logistics Warehousing technology entirely, and have an `on_research_finished` event listener unlock logistic warehouse/storehouse recipes as appropriate depending on the sequence in which Warehousing, Construction Robotics, and Logistic System are unlocked.

I can see a case for either option. One might argue that if Warehousing is available, the logistic variants should become available automatically when the logistic technologies are researched, just like chests. The main case against this is that steel chests, required to make logistic variants, are unlocked naturally along the path to robots, because engines require steel. Warehouses are nowhere in this natural research chain, though they are available to research at any time between unlocking steel processing and unlocking robots.

Anyway, as mentioned already, it's well past 2am and I should be sleeping. Either solution will take some time to develop and test. So, regardless of which option ultimately makes it into the mod, I'm going to finalize and release 0.1.1 first to get the basic research tweaks—and more importantly, buffer warehouses—out to players sooner. (I already pushed back my target release date once, and I'm not delaying it again. 😆 )

**Comment by dgw** [comment]
I'm pushing this off, because I want to get 0.1.3 out in the next few days (mostly for translation updates) and this is going to be more than I can get done in that time.

@Anoyomouse Thinking research rebalance would go well with the Factorio 0.17 update, what say you?

**Comment by Anoyomouse** [comment]
@dgw Yeah, for 0.17 go nuts, i think it's been far too long that it's been stuck where it is.

**Comment by dgw** [comment]
[FFF 269](https://factorio.com/blog/post/fff-269) today announced Factorio 0.17 is planned to release in January 2019. That's a good target for getting this done.

**Comment by dgw** [comment]
[FFF 275](https://factorio.com/blog/post/fff-275) today  detailed a pretty massive overhaul of science in the base game. With that information now public, this rebalancing can go to concept stage.

**Comment by dgw** [comment]
Put in some work on this, which will soon appear in #59 (once I've figured out exactly what changes to stage for commit, and which are for something else).

@mkaito, if you still use this mod, your feedback on this and other changes in #59 would be welcome!
